apiVersion: apps/v1
kind: Deployment
metadata:
  name: season-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: season-service
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: season-service
    spec:
      containers:
        - name: season-service
          image: outoftheparkacr.azurecr.io/season-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: season-http
---
apiVersion: v1
kind: Service
metadata:
  name: season-service-deployment
  namespace: default
spec:
  ports:
    - name: season-http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: season-service
  type: ClusterIP